### ISSUE TITLE
ace function generating errors & NaNs

### ISSUE THREAD

**Issue by noraheaphy** [noraheaphy/finalproject#1]
Hi Casey and Lauren,

I have a rooted tree `Ocampo_Portulaca.parts.treefile` and character data `portulaca_means_11-06-2020.csv` that I've successfully mapped onto the tips, following the R code from Exercise 10. But when I use the ace function for ancestral reconstruction, I get an error that says "NaNs produced NA/Inf replaced by maximum positive value...The likelihood gradient seems flat in at least one dimension (gradient null): cannot compute the standard-errors of the transition rates." It then prints out the reconstructed internal node values, residual log likelihood, etc. but all the confidence interval values are NaN. This seems to be only a problem reconstructing with REML, not with PIC, but I worry it points to a deeper problem somewhere.

I think you should be able to reproduce the error using the two input files and the `ancestral_reconstruction.Rmd`. Let me know if you have some idea of what I'm doing wrong. I did have to root the tree manually based on the Ocampo & Columbus 2012 rooted tree as a temporary fix, since the phylogeny I got from the lab didn't come rooted. 

Thanks!

[tree file](https://github.com/noraheaphy/finalproject/blob/master/data/Ocampo_Portulaca.parts.treefile)
[character data csv](https://github.com/noraheaphy/finalproject/blob/master/data/portulaca_means_11-06-2020.csv)
[ancestral reconstruction Rmd](https://github.com/noraheaphy/finalproject/blob/master/scripts/ancestral_reconstruct.Rmd)

**Comment by caseywdunn** [comment]
Hi @noraheaphy (cc @lemellenthin) -
     I was able to reproduce the warning that you describe at https://github.com/noraheaphy/finalproject/blob/6f981379a763f6e2a83faa49bb12442355f89b2e/scripts/ancestral_reconstruct.Rmd#L219. At that pint, I double checked name correspondence

```
> names(portulacaData)
 [1] "Portulaca amilis"        "Portulaca australis"     "Portulaca bicolor"       "Portulaca confertifolia"
 [5] "Portulaca cryptopetala"  "Portulaca decipiens"     "Portulaca digyna"        "Portulaca elatior"      
 [9] "Portulaca eruca"         "Portulaca filifolia"     "Portulaca fluvialis"     "Portulaca foliosa"      
[13] "Portulaca hereroensis"   "Portulaca hirsutissima"  "Portulaca intraterranea" "Portulaca mexicana"     
[17] "Portulaca mucronata"     "Portulaca obtusa"        "Portulaca oligosperma"   "Portulaca perennis"     
[21] "Portulaca quadrifida"    "Portulaca rubricaulis"   "Portulaca suffrutescens" "Portulaca umbraticola"  
[25] "Portulaca wightiana"    
> portulacaTree$tip.label
 [1] "Portulaca bicolor"       "Portulaca digyna"        "Portulaca wightiana"     "Portulaca quadrifida"   
 [5] "Portulaca hereroensis"   "Portulaca umbraticola"   "Portulaca amilis"        "Portulaca perennis"     
 [9] "Portulaca obtusa"        "Portulaca eruca"         "Portulaca confertifolia" "Portulaca mexicana"     
[13] "Portulaca suffrutescens" "Portulaca fluvialis"     "Portulaca rubricaulis"   "Portulaca foliosa"      
[17] "Portulaca decipiens"     "Portulaca filifolia"     "Portulaca australis"     "Portulaca elatior"      
[21] "Portulaca intraterranea" "Portulaca cryptopetala"  "Portulaca mucronata"     "Portulaca hirsutissima" 
[25] "Portulaca oligosperma" 
```

The tip and data names are not in the same order. So I went through the code upstream. Here are a few things I noticed:
- The `here` file path specification made reproduction a bit difficult. I replaced it with relative `data/` paths. There were also two files in the repo named `ancestral_reconstruct.Rmd`, one in the root and one in the `scripts/` directory. I worked off the file in the `scripts/` directory, but placed it in the root (replacing the other file) to get the paths to work.
- There are a few places where columns of data frames are extracted as vectors, and then typed as dataframes. For example `data.frame(portulacaTree$tip.label)`.
- Sometimes `.` is used in place of a `$` to designate a column, which throws and error. eg `portulacaTree.tip.label` instead of `portulacaTree$tip.label`
- There were a few places where things were done with data frames that could be done directly with vectors, which is cleaner. For example, I refactored the following bit:

```
portulacaTree$tip.label = portulacaTree$tip.label %>%
  str_replace("-.*","") %>%
  str_replace("_", " ")
```
- The following call was removing all columns except for `MAT`:

```
portulacaData <- portulacaData %>% remove_rownames %>% 
  column_to_rownames(var = "species") %>%
  select(MAT)
```

Instead, I kept the data frame the same and added row.names with `row.names(portulacaData) = portulacaData$species`

- And now for a bigger problem, the terms in the match example I provided in the exercise were reversed! So they weren't ordering things correctly. That line should be `portulacaData <- portulacaData[match(portulacaTree$tip.label,row.names(portulacaData)), ]`. Sorry about that.

I can't push to the repo or attach a rmd file, so I attached it here as a zip.

[ancestral_reconstruct.Rmd.zip](https://github.com/noraheaphy/finalproject/files/5547015/ancestral_reconstruct.Rmd.zip)


Now that the upstream issues are addressed.... we still get the same warning! But it puts us in a better place to understand it.

**Comment by caseywdunn** [comment]
Ancestral character state estimation tools can do very strange things when there are edge lengths of `0`. I checked with `portulacaTree$edge.length`, and there is an edge of length 0. That is why the tree is binary ()each internal node has two daughter nodes), even though the three deepest edges all start at nodes of the same age.

**Comment by caseywdunn** [comment]
Yup, that is it! adding this before the `ace` call fixes it - `portulacaTree$edge.length[portulacaTree$edge.length==0] = 1e-6`.

This line finds all edges with length 0, then sets their value to a super tiny number using the scientific notation for one millionth.

**Comment by noraheaphy** [comment]
Thank you! That worked for me!
